/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Character {
  'id' : bigint,
  'characterClass' : { 'warrior' : null } |
    { 'mage' : null } |
    { 'ranger' : null },
  'owner' : Principal,
  'appearance' : { 'equipment' : string, 'hair' : string, 'skinTone' : string },
  'ultimateCharged' : boolean,
  'name' : string,
  'race' : { 'elf' : null } |
    { 'human' : null } |
    { 'dwarf' : null },
  'stats' : {
    'strength' : bigint,
    'agility' : bigint,
    'intelligence' : bigint,
  },
  'skillPoints' : bigint,
  'abilities' : Array<string>,
}
export interface Guild {
  'id' : bigint,
  'members' : Array<Principal>,
  'name' : string,
  'leader' : Principal,
}
export interface Quest {
  'id' : bigint,
  'completedBy' : Array<Principal>,
  'reward' : { 'exp' : bigint, 'gold' : bigint },
  'title' : string,
  'isMainQuest' : boolean,
  'description' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'item' : string,
  'seller' : Principal,
  'timestamp' : Time,
  'buyer' : Principal,
  'price' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'createdAt' : Time,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WeatherState = { 'clear' : null } |
  { 'rain' : null } |
  { 'storm' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeQuest' : ActorMethod<[bigint, bigint], undefined>,
  'createCharacter' : ActorMethod<
    [
      string,
      { 'elf' : null } |
        { 'human' : null } |
        { 'dwarf' : null },
      { 'warrior' : null } |
        { 'mage' : null } |
        { 'ranger' : null },
      { 'equipment' : string, 'hair' : string, 'skinTone' : string },
    ],
    bigint
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createGuild' : ActorMethod<[string], bigint>,
  'createQuest' : ActorMethod<
    [string, string, { 'exp' : bigint, 'gold' : bigint }, boolean],
    bigint
  >,
  'createTransaction' : ActorMethod<[Principal, string, bigint], bigint>,
  'getAllCharacters' : ActorMethod<[], Array<Character>>,
  'getAllGuilds' : ActorMethod<[], Array<Guild>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCharacter' : ActorMethod<[bigint], Character>,
  'getGuild' : ActorMethod<[bigint], Guild>,
  'getQuest' : ActorMethod<[bigint], Quest>,
  'getQuests' : ActorMethod<[boolean], Array<Quest>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTransaction' : ActorMethod<[bigint], Transaction>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTransactions' : ActorMethod<[], Array<Transaction>>,
  'getWeather' : ActorMethod<[], WeatherState>,
  'get_world_state' : ActorMethod<
    [],
    { 'timestamp' : Time, 'weather' : WeatherState }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'joinGuild' : ActorMethod<[bigint], undefined>,
  'leaveGuild' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setWeather' : ActorMethod<[WeatherState], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCharacterSkills' : ActorMethod<
    [bigint, bigint, Array<string>],
    undefined
  >,
  'updateCharacterUltimate' : ActorMethod<[bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];