/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Character = IDL.Record({
  'id' : IDL.Nat,
  'characterClass' : IDL.Variant({
    'warrior' : IDL.Null,
    'mage' : IDL.Null,
    'ranger' : IDL.Null,
  }),
  'owner' : IDL.Principal,
  'appearance' : IDL.Record({
    'equipment' : IDL.Text,
    'hair' : IDL.Text,
    'skinTone' : IDL.Text,
  }),
  'ultimateCharged' : IDL.Bool,
  'name' : IDL.Text,
  'race' : IDL.Variant({
    'elf' : IDL.Null,
    'human' : IDL.Null,
    'dwarf' : IDL.Null,
  }),
  'stats' : IDL.Record({
    'strength' : IDL.Nat,
    'agility' : IDL.Nat,
    'intelligence' : IDL.Nat,
  }),
  'skillPoints' : IDL.Nat,
  'abilities' : IDL.Vec(IDL.Text),
});
export const Guild = IDL.Record({
  'id' : IDL.Nat,
  'members' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'leader' : IDL.Principal,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Opt(IDL.Text),
});
export const Quest = IDL.Record({
  'id' : IDL.Nat,
  'completedBy' : IDL.Vec(IDL.Principal),
  'reward' : IDL.Record({ 'exp' : IDL.Nat, 'gold' : IDL.Nat }),
  'title' : IDL.Text,
  'isMainQuest' : IDL.Bool,
  'description' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'item' : IDL.Text,
  'seller' : IDL.Principal,
  'timestamp' : Time,
  'buyer' : IDL.Principal,
  'price' : IDL.Nat,
});
export const WeatherState = IDL.Variant({
  'clear' : IDL.Null,
  'rain' : IDL.Null,
  'storm' : IDL.Null,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeQuest' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'createCharacter' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'elf' : IDL.Null,
          'human' : IDL.Null,
          'dwarf' : IDL.Null,
        }),
        IDL.Variant({
          'warrior' : IDL.Null,
          'mage' : IDL.Null,
          'ranger' : IDL.Null,
        }),
        IDL.Record({
          'equipment' : IDL.Text,
          'hair' : IDL.Text,
          'skinTone' : IDL.Text,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createGuild' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createQuest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Record({ 'exp' : IDL.Nat, 'gold' : IDL.Nat }),
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'createTransaction' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getAllGuilds' : IDL.Func([], [IDL.Vec(Guild)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCharacter' : IDL.Func([IDL.Nat], [Character], ['query']),
  'getGuild' : IDL.Func([IDL.Nat], [Guild], ['query']),
  'getQuest' : IDL.Func([IDL.Nat], [Quest], ['query']),
  'getQuests' : IDL.Func([IDL.Bool], [IDL.Vec(Quest)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getWeather' : IDL.Func([], [WeatherState], ['query']),
  'get_world_state' : IDL.Func(
      [],
      [IDL.Record({ 'timestamp' : Time, 'weather' : WeatherState })],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'joinGuild' : IDL.Func([IDL.Nat], [], []),
  'leaveGuild' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setWeather' : IDL.Func([WeatherState], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCharacterSkills' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateCharacterUltimate' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Character = IDL.Record({
    'id' : IDL.Nat,
    'characterClass' : IDL.Variant({
      'warrior' : IDL.Null,
      'mage' : IDL.Null,
      'ranger' : IDL.Null,
    }),
    'owner' : IDL.Principal,
    'appearance' : IDL.Record({
      'equipment' : IDL.Text,
      'hair' : IDL.Text,
      'skinTone' : IDL.Text,
    }),
    'ultimateCharged' : IDL.Bool,
    'name' : IDL.Text,
    'race' : IDL.Variant({
      'elf' : IDL.Null,
      'human' : IDL.Null,
      'dwarf' : IDL.Null,
    }),
    'stats' : IDL.Record({
      'strength' : IDL.Nat,
      'agility' : IDL.Nat,
      'intelligence' : IDL.Nat,
    }),
    'skillPoints' : IDL.Nat,
    'abilities' : IDL.Vec(IDL.Text),
  });
  const Guild = IDL.Record({
    'id' : IDL.Nat,
    'members' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'leader' : IDL.Principal,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Opt(IDL.Text),
  });
  const Quest = IDL.Record({
    'id' : IDL.Nat,
    'completedBy' : IDL.Vec(IDL.Principal),
    'reward' : IDL.Record({ 'exp' : IDL.Nat, 'gold' : IDL.Nat }),
    'title' : IDL.Text,
    'isMainQuest' : IDL.Bool,
    'description' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'item' : IDL.Text,
    'seller' : IDL.Principal,
    'timestamp' : Time,
    'buyer' : IDL.Principal,
    'price' : IDL.Nat,
  });
  const WeatherState = IDL.Variant({
    'clear' : IDL.Null,
    'rain' : IDL.Null,
    'storm' : IDL.Null,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeQuest' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'createCharacter' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'elf' : IDL.Null,
            'human' : IDL.Null,
            'dwarf' : IDL.Null,
          }),
          IDL.Variant({
            'warrior' : IDL.Null,
            'mage' : IDL.Null,
            'ranger' : IDL.Null,
          }),
          IDL.Record({
            'equipment' : IDL.Text,
            'hair' : IDL.Text,
            'skinTone' : IDL.Text,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createGuild' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createQuest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Record({ 'exp' : IDL.Nat, 'gold' : IDL.Nat }),
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'createTransaction' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getAllGuilds' : IDL.Func([], [IDL.Vec(Guild)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCharacter' : IDL.Func([IDL.Nat], [Character], ['query']),
    'getGuild' : IDL.Func([IDL.Nat], [Guild], ['query']),
    'getQuest' : IDL.Func([IDL.Nat], [Quest], ['query']),
    'getQuests' : IDL.Func([IDL.Bool], [IDL.Vec(Quest)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getWeather' : IDL.Func([], [WeatherState], ['query']),
    'get_world_state' : IDL.Func(
        [],
        [IDL.Record({ 'timestamp' : Time, 'weather' : WeatherState })],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'joinGuild' : IDL.Func([IDL.Nat], [], []),
    'leaveGuild' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setWeather' : IDL.Func([WeatherState], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCharacterSkills' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateCharacterUltimate' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };